version: '2'
services:
    devdemo-app:
        image: devdemo
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://devdemo-postgresql:5432/devdemo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    devdemo-postgresql:
        extends:
            file: postgresql.yml
            service: devdemo-postgresql
