version: '2'
services:
    devdemo-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/devdemo/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=devdemo
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
